# Site settings
title: Utecht Blog 
email: joseph.utecht@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Some musings about coding.
  Currently exploring graph datastores.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://utecht.github.io" # the base hostname & protocol for your site
twitter_username: thenmal
github_username:  utecht

# Build settings
markdown: kramdown
