# General
name: Utecht Blog
description: "Random thoughts and slightly collected notes about things I do."
url: http://localhost:4000

markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
twitter: thenmal
github: utecht

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
